import pyttsx3
engine = pyttsx3.init()
print("I am ready")
inp = input()
file = input()
voice = int(input())
engine.setProperty("rate", 150)
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[voice].id)
engine.save_to_file(inp, file)
engine.runAndWait()
print("Completed succesfully")